---
title: "Lecture 10: Clustering (Lab)"
output:
  html_document:
  df_print: paged
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



## The Iris Dataset

We will use the `iris` dataset.

```{r}
head(iris)
```

```{r}
library(ggplot2)
library(dplyr)
iris_value <- iris %>% dplyr::select(Petal.Length, Petal.Width)
iris_label <- iris$Species
ggplot(iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, color = Species))
```


## $K$-means clustering

```{r}
fit <- kmeans(iris_value, centers = 3)
fit
fit$cluster
fit$centers
```


### Visualization
```{r}
iris <- iris %>% mutate(cluster = factor(fit$cluster))
ggplot(iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, shape = cluster))
ggplot(iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, shape = cluster,
                           color = Species))
```

Now, let's try to cluster into 2 clusters.
```{r}
fit <- kmeans(iris_value, centers = 2)
fit$cluster
fit$centers
```


### Visualization
```{r}
iris <- iris %>% mutate(cluster = factor(fit$cluster))
ggplot(iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, shape = cluster,
                           color = Species))
```

## Hierarchical Clustering

```{r}
hc.complete <- hclust(dist(iris_value), method = "complete")
hc.average <- hclust(dist(iris_value), method = "average")
hc.single <- hclust(dist(iris_value), method = "single")
```

```{r}
par(mfrow = c(1, 3))
plot(hc.complete, main = "Complete Linkage",
xlab = "", sub = "", cex = .9)
plot(hc.average, main = "Average Linkage",
xlab = "", sub = "", cex = .9)
plot(hc.single, main = "Single Linkage",
xlab = "", sub = "", cex = .9)
```

```{r}
cutree(hc.complete, 2)
cutree(hc.complete, 3)
```

### Visualization
```{r}
iris$cluster <- factor(cutree(hc.complete, 3))
ggplot(iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, shape = cluster,
                           color = Species))
```

When the features are not measured on the same scale, we need to scale the data before clustering. (Here, scaling is not necessary as both features are lengths of the same units.)

```{r}
xsc <- scale(iris_value)
hc <- hclust(dist(xsc), method = "complete")
plot(hc, main = "Hierarchical Clustering with Scaled Features")
dend1 <- as.dendrogram(hc)
plot(dend1)
dend2 <- cut(dend1, h = 2)
plot(dend2$upper)
```


